{% set name = "cmocka" %}
{% set version = "1.1.8" %}
{% set version_major_minor = ".".join(version.split('.')[:2]) %}
{% set so_version = "0.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cmocka.org/files/{{ version_major_minor }}/{{ name }}-{{ version }}.tar.xz
  sha256: 58435b558766d7f4c729ba163bdf3aec38bed3bc766dab684e3526ed0aa7c780

build:
  number: 0
  run_exports:
    # No correlation between library name and
    # so names
    # https://gitlab.com/cmocka/cmocka/-/issues/43
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make   # [unix]
    - ninja  # [not unix]

test:
  commands:
    - test -f $PREFIX/lib/libcmocka${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libcmocka${SHLIB_EXT}.{{ so_version }}  # [linux]
    - test -f $PREFIX/lib/libcmocka.{{ so_version }}${SHLIB_EXT}  # [osx]
    - test -f $PREFIX/include/cmocka.h      # [unix]
    - if not exist %LIBRARY_BIN%\\cmocka.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\cmocka.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\\cmocka.h exit 1     # [win]

about:
  home: https://cmocka.org/
  license: Apache-2.0
  license_family: Apache
  license_file: COPYING
  summary: An elegant unit testing framework for C with support for mock objects.

  description: |
    cmocka is an elegant unit testing framework for C with support 
    for mock objects. It only requires the standard C library, 
    works on a range of computing platforms (including embedded) 
    and with different compilers.

  dev_url: https://gitlab.com/cmocka/cmocka
extra:
  recipe-maintainers:
    - hmaarrfk
